"""
Generates a standalone, config-specific Python runner script for advanced-
mode users who want to run their campaign entirely locally with no Streamlit
or login.

The generated script only depends on core/baybe_integration.py (and its
own dependencies: baybe, torch, gpytorch, botorch, scipy, pandas, numpy) --
none of the web-app pieces (db/, ui/, streamlit, supabase, auth0).
"""

import json


def generate_standalone_script(config: dict, campaign_name: str) -> str:
    config_literal = json.dumps(config, indent=4)

    return f'''"""
Standalone local runner for campaign: {campaign_name}

Generated by metabolize (advanced mode). Runs entirely locally, no login required.

REQUIREMENTS:
    Place this file in the same directory as (or adjust the import path
    to) core/baybe_integration.py and its dependencies (meta_blender module, acquisition_switcher module).
    Install:
        pip install baybe torch gpytorch botorch scipy pandas numpy matplotlib

USAGE:
    Assign RESULTS_CSV, BLEND_LOG_CSV and STATS_DIR paths, and SOBOL_SEED as needed.
    python {campaign_name.lower().replace(" ", "_")}_runner.py

Each round, this script:
  1. Generates (or, for round 0, generates via Sobol) a batch of
     recommended experiments and saves them to a CSV run sheet.
  2. Pauses and asks you to open that CSV, run the experiments, fill in
     the target column, save it, and press Enter to continue.
  3. Reads the filled-in results back in, appends them to the running
     history, and generates the next round's recommendations.
  4. Repeats until you've completed the configured number of rounds, then
     asks whether to continue with more rounds or stop.
  5. After every round, saves charts and tables (learning curve, progress,
     distribution, blend weights, per-parameter analysis, top results) to
     STATS_DIR. This is kept current as you go, not just at the very end.

All results accumulate in RESULTS_CSV in this script's directory.
"""

import sys
import os
import warnings

warnings.filterwarnings("ignore")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import pandas as pd
import matplotlib.pyplot as plt
from core.baybe_integration import generate_sobol_init, recommend_next_batch

CONFIG = {config_literal}

CAMPAIGN_NAME = {campaign_name!r}

# Edit these paths and values as needed. The script will create the stats folder if it doesn't exist.
RESULTS_CSV = "/your/path/here/all_results.csv"
BLEND_LOG_CSV = "/your/path/here/blend_log.csv"
STATS_DIR = "/your/path/here/stats"
SOBOL_SEED = 67


def _param_columns():
    return [p["name"] for p in CONFIG["parameters"]]


def _pause_for_results(run_sheet_path: str) -> pd.DataFrame:
    print(f"\\nRun sheet saved to: {{run_sheet_path}}")
    print(f"Fill in the '{{CONFIG['target_name']}}' column with your real results, save the file, "
          f"then press Enter here to continue. Yield values must be between 0 and 1 (e.g. 0.75 for 75%).")
    input()
    df = pd.read_csv(run_sheet_path)
    if df[CONFIG["target_name"]].isna().any():
        print(f"Some rows are still missing {{CONFIG['target_name']}} or invalid value(s) entered. Please fill in every row.")
        return _pause_for_results(run_sheet_path)
    return df


def _load_history() -> pd.DataFrame:
    if os.path.exists(RESULTS_CSV):
        return pd.read_csv(RESULTS_CSV)
    return pd.DataFrame(columns=_param_columns() + [CONFIG["target_name"], "batch"])


def _append_history(history_df: pd.DataFrame, new_df: pd.DataFrame, round_number: int) -> pd.DataFrame:
    new_df = new_df.copy()
    new_df["batch"] = round_number
    combined = pd.concat([history_df, new_df], ignore_index=True)
    combined.to_csv(RESULTS_CSV, index=False)
    return combined

def _log_blend_decision(round_number: int, blend_output: dict) -> None:
    """Append this round's UCB/EI/PI weights and reason to blend_log.csv,
    so _save_stats() can plot the weight trajectory later (this isn't
    otherwise persisted anywhere, unlike in the web app's database)."""
    row = {{
        "round": round_number,
        "UCB": blend_output["weights"].get("UCB"),
        "EI": blend_output["weights"].get("EI"),
        "PI": blend_output["weights"].get("PI"),
        "reason": blend_output.get("reason", ""),
    }}
    log_df = pd.DataFrame([row])
    if os.path.exists(BLEND_LOG_CSV):
        log_df = pd.concat([pd.read_csv(BLEND_LOG_CSV), log_df], ignore_index=True)
    log_df.to_csv(BLEND_LOG_CSV, index=False)

def _save_stats(history_df: pd.DataFrame) -> None:
    """Save charts and tables to STATS_DIR, mirroring the web app's stats
    page. Called after every round so the folder stays current as you go,
    not just at the very end."""
    os.makedirs(STATS_DIR, exist_ok=True)
    target = CONFIG["target_name"]
 
    df = history_df.sort_values(["batch"]).reset_index(drop=True)
    df["trial_index"] = df.index + 1
    df["best_so_far"] = df[target].cummax()
 
    # ---- learning curve ----
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(df["trial_index"], df[target], "o", alpha=0.5, label=target)
    ax.plot(df["trial_index"], df["best_so_far"], "-", label="Best so far")
    ax.set_xlabel("Experiment #")
    ax.set_ylabel(target)
    ax.set_title("Learning curve")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(STATS_DIR, "learning_curve.png"))
    plt.close(fig)
 
    # ---- best-so-far by round ----
    per_round_best = df.groupby("batch")["best_so_far"].max()
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(per_round_best.index, per_round_best.values, "-o")
    ax.set_xlabel("Round")
    ax.set_ylabel(f"Best {{target}} so far")
    ax.set_title("Progress over rounds")
    fig.tight_layout()
    fig.savefig(os.path.join(STATS_DIR, "progress_by_round.png"))
    plt.close(fig)
 
    # ---- objective distribution ----
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.hist(df[target], bins=10, edgecolor="black")
    ax.set_xlabel(target)
    ax.set_ylabel("Count")
    ax.set_title(f"{{target}} distribution")
    fig.tight_layout()
    fig.savefig(os.path.join(STATS_DIR, "distribution.png"))
    plt.close(fig)
 
    # ---- blend weight trajectory ----
    if os.path.exists(BLEND_LOG_CSV):
        blend_df = pd.read_csv(BLEND_LOG_CSV).sort_values("round")
        fig, ax = plt.subplots(figsize=(8, 4))
        for col in ["UCB", "EI", "PI"]:
            ax.plot(blend_df["round"], blend_df[col], "-o", label=col)
        ax.set_xlabel("Round")
        ax.set_ylabel("Weight")
        ax.set_title("Acquisition blend weights per round")
        ax.legend()
        fig.tight_layout()
        fig.savefig(os.path.join(STATS_DIR, "blend_weights.png"))
        plt.close(fig)
 
    # ---- per-parameter analysis ----
    for p in CONFIG["parameters"]:
        p_name = p["name"]
        if p_name not in df.columns:
            continue
        fig, ax = plt.subplots(figsize=(8, 4))
        if p["type"] == "categorical":
            summary = df.groupby(p_name)[target].mean().sort_values(ascending=False)
            ax.bar(summary.index.astype(str), summary.values)
            ax.set_ylabel(f"Mean {{target}}")
        else:
            ax.scatter(df[p_name], df[target], alpha=0.6)
            ax.set_ylabel(target)
        ax.set_xlabel(p_name)
        ax.set_title(f"{{p_name}} vs {{target}}")
        fig.tight_layout()
        safe_name = p_name.replace(" ", "_").replace("/", "_")
        fig.savefig(os.path.join(STATS_DIR, f"param_{{safe_name}}.png"))
        plt.close(fig)
 
    # ---- tables ----
    top_n = min(10, len(df))
    top_df = df.nlargest(top_n, target)[["trial_index", "batch", target] + _param_columns()]
    top_df.to_csv(os.path.join(STATS_DIR, "top_results.csv"), index=False)
 
    print(f"Stats saved to {{STATS_DIR}}/")

def main():
    print(f"=== {{CAMPAIGN_NAME}} -- standalone local runner ===")
    history_df = _load_history()

    # ---- round 0: init ----
    if history_df.empty:
        print(f"\\nGenerating initial batch ({{CONFIG['init_size']}} experiments, Sobol seed={{SOBOL_SEED}})...")
        init_df = generate_sobol_init(CONFIG, seed=SOBOL_SEED)
        init_df[CONFIG["target_name"]] = ""
        run_sheet_path = "round0_run_sheet.csv"
        init_df.to_csv(run_sheet_path, index=False)
        filled = _pause_for_results(run_sheet_path)
        history_df = _append_history(history_df, filled, round_number=0)
        print(f"Round 0 ingested. Best {{CONFIG['target_name']}} so far: "
              f"{{history_df[CONFIG['target_name']].max():.4g}}")
        _save_stats(history_df)

    # ---- rounds 1..n_rounds (and beyond, if the user chooses to continue) ----
    round_number = int(history_df["batch"].max()) + 1
    n_rounds = CONFIG["n_rounds"]

    while True:
        if round_number > n_rounds:
            again = input(
                f"\\nYou've completed all {{n_rounds}} planned rounds. "
                f"Run another round? [y/N]: "
            )
            if again.strip().lower() != "y":
                break

        print(f"\\nGenerating round {{round_number}} recommendations...")
        result = recommend_next_batch(
            CONFIG, history_df,
            batch_size=CONFIG["batch_size"],
            total_batches=n_rounds,
        )
        print(f"  {{result['blend']['reason']}}")
        if result["actual_batch_size"] < result["requested_batch_size"]:
            print(f"  Only {{result['actual_batch_size']}} new unique combinations remain "
                  f"(requested {{result['requested_batch_size']}}).")
        _log_blend_decision(round_number, result["blend"])

        recs = result["recommendations"][_param_columns()].copy()
        recs[CONFIG["target_name"]] = ""
        run_sheet_path = f"round{{round_number}}_run_sheet.csv"
        recs.to_csv(run_sheet_path, index=False)

        filled = _pause_for_results(run_sheet_path)
        history_df = _append_history(history_df, filled, round_number=round_number)
        print(f"Round {{round_number}} ingested. Best {{CONFIG['target_name']}} so far: "
              f"{{history_df[CONFIG['target_name']].max():.4g}}")
        _save_stats(history_df)

        round_number += 1

    print(f"\\nDone. Full results saved to {{RESULTS_CSV}}.")
    print(f"Best {{CONFIG['target_name']}}: {{history_df[CONFIG['target_name']].max():.4g}}")


if __name__ == "__main__":
    main()
'''